INFO 2025-04-30 21:55:20,680 autoreload Watching for file changes with StatReloader
INFO 2025-04-30 21:56:26,075 autoreload C:\Users\chang\Documents\Python_Projects\DojoTest2\portal\views.py changed, reloading.
INFO 2025-04-30 21:56:28,846 autoreload Watching for file changes with StatReloader
INFO 2025-04-30 21:56:33,551 autoreload C:\Users\chang\Documents\Python_Projects\DojoTest2\portal\views.py changed, reloading.
INFO 2025-04-30 21:56:36,513 autoreload Watching for file changes with StatReloader
INFO 2025-04-30 21:56:56,654 autoreload C:\Users\chang\Documents\Python_Projects\DojoTest2\portal\models.py changed, reloading.
INFO 2025-04-30 21:56:59,601 autoreload Watching for file changes with StatReloader
INFO 2025-04-30 21:59:16,038 autoreload C:\Users\chang\Documents\Python_Projects\DojoTest2\student_portal\chat\consumers.py changed, reloading.
INFO 2025-04-30 21:59:19,003 autoreload Watching for file changes with StatReloader
INFO 2025-04-30 21:59:34,811 autoreload Watching for file changes with StatReloader
INFO 2025-04-30 21:59:39,283 runserver [mHTTP GET /api/calendar/events/?start=2025-03-30T00%3A00%3A00-04%3A00&end=2025-05-11T00%3A00%3A00-04%3A00 200 [0.04, 127.0.0.1:51913][0m
INFO 2025-04-30 21:59:40,319 runserver [mHTTP GET /student_dashboard/ 200 [0.12, 127.0.0.1:51913][0m
INFO 2025-04-30 21:59:40,583 runserver [36mHTTP GET /static/admin/js/vendor/jquery/jquery.min.js 304 [0.03, 127.0.0.1:51913][0m
INFO 2025-04-30 21:59:40,594 runserver [36mHTTP GET /static/dist/css/adminlte.min.css 304 [0.03, 127.0.0.1:51914][0m
INFO 2025-04-30 21:59:40,596 runserver [36mHTTP GET /static/plugins/fontawesome-free/css/all.min.css 304 [0.03, 127.0.0.1:51916][0m
INFO 2025-04-30 21:59:40,601 runserver [36mHTTP GET /static/plugins/overlayScrollbars/css/OverlayScrollbars.min.css 304 [0.03, 127.0.0.1:51915][0m
INFO 2025-04-30 21:59:40,608 runserver [36mHTTP GET /static/admin/css/forms.css 304 [0.03, 127.0.0.1:51917][0m
INFO 2025-04-30 21:59:40,612 runserver [36mHTTP GET /static/admin/css/widgets.css 304 [0.03, 127.0.0.1:51918][0m
INFO 2025-04-30 21:59:40,633 runserver [36mHTTP GET /static/plugins/summernote/summernote-bs4.min.css 304 [0.03, 127.0.0.1:51913][0m
INFO 2025-04-30 21:59:40,635 runserver [36mHTTP GET /static/plugins/icheck-bootstrap/icheck-bootstrap.min.css 304 [0.02, 127.0.0.1:51914][0m
INFO 2025-04-30 21:59:40,637 runserver [36mHTTP GET /static/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css 304 [0.03, 127.0.0.1:51916][0m
INFO 2025-04-30 21:59:40,641 runserver [36mHTTP GET /static/plugins/daterangepicker/daterangepicker.css 304 [0.02, 127.0.0.1:51915][0m
INFO 2025-04-30 21:59:40,648 runserver [36mHTTP GET /static/plugins/toastr/toastr.min.css 304 [0.02, 127.0.0.1:51917][0m
INFO 2025-04-30 21:59:40,652 runserver [36mHTTP GET /static/plugins/jqvmap/jqvmap.min.css 304 [0.02, 127.0.0.1:51918][0m
INFO 2025-04-30 21:59:40,661 runserver [36mHTTP GET /static/plugins/bootstrap/js/bootstrap.bundle.min.js 304 [0.02, 127.0.0.1:51913][0m
INFO 2025-04-30 21:59:40,667 runserver [36mHTTP GET /static/images/logo.png 304 [0.02, 127.0.0.1:51914][0m
INFO 2025-04-30 21:59:40,669 runserver [36mHTTP GET /static/dist/img/user1-128x128.jpg 304 [0.01, 127.0.0.1:51916][0m
INFO 2025-04-30 21:59:40,697 runserver [36mHTTP GET /static/dist/img/user3-128x128.jpg 304 [0.01, 127.0.0.1:51914][0m
INFO 2025-04-30 21:59:40,698 runserver [36mHTTP GET /static/dist/img/user8-128x128.jpg 304 [0.01, 127.0.0.1:51916][0m
INFO 2025-04-30 21:59:40,753 runserver [36mHTTP GET /static/plugins/jquery/jquery.min.js 304 [0.00, 127.0.0.1:51914][0m
INFO 2025-04-30 21:59:40,773 runserver [36mHTTP GET /static/plugins/chart.js/Chart.min.js 304 [0.02, 127.0.0.1:51918][0m
INFO 2025-04-30 21:59:40,775 runserver [36mHTTP GET /static/plugins/jquery-ui/jquery-ui.min.js 304 [0.02, 127.0.0.1:51913][0m
INFO 2025-04-30 21:59:40,779 runserver [36mHTTP GET /static/dist/js/demo.js 304 [0.02, 127.0.0.1:51917][0m
INFO 2025-04-30 21:59:40,781 runserver [36mHTTP GET /static/dist/js/adminlte.min.js 304 [0.03, 127.0.0.1:51916][0m
INFO 2025-04-30 21:59:40,782 runserver [36mHTTP GET /static/plugins/sparklines/sparkline.js 304 [0.03, 127.0.0.1:51915][0m
INFO 2025-04-30 21:59:40,790 runserver [36mHTTP GET /static/dist/img/user2-160x160.jpg 304 [0.02, 127.0.0.1:51914][0m
INFO 2025-04-30 21:59:40,822 runserver [36mHTTP GET /static/plugins/fontawesome-free/webfonts/fa-solid-900.woff2 304 [0.02, 127.0.0.1:51914][0m
INFO 2025-04-30 21:59:40,829 runserver [36mHTTP GET /static/plugins/fontawesome-free/webfonts/fa-regular-400.woff2 304 [0.02, 127.0.0.1:51916][0m
INFO 2025-04-30 21:59:40,831 runserver [36mHTTP GET /static/plugins/jqvmap/maps/jquery.vmap.usa.js 304 [0.02, 127.0.0.1:51917][0m
INFO 2025-04-30 21:59:40,833 runserver [36mHTTP GET /static/plugins/jqvmap/jquery.vmap.min.js 304 [0.03, 127.0.0.1:51915][0m
INFO 2025-04-30 21:59:40,834 runserver [36mHTTP GET /static/plugins/jquery-knob/jquery.knob.min.js 304 [0.02, 127.0.0.1:51913][0m
INFO 2025-04-30 21:59:40,836 runserver [36mHTTP GET /static/plugins/moment/moment.min.js 304 [0.02, 127.0.0.1:51918][0m
INFO 2025-04-30 21:59:40,859 runserver [36mHTTP GET /static/plugins/daterangepicker/daterangepicker.js 304 [0.02, 127.0.0.1:51914][0m
INFO 2025-04-30 21:59:40,868 runserver [36mHTTP GET /static/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js 304 [0.02, 127.0.0.1:51918][0m
INFO 2025-04-30 21:59:40,871 runserver [36mHTTP GET /static/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js 304 [0.02, 127.0.0.1:51913][0m
INFO 2025-04-30 21:59:40,874 runserver [36mHTTP GET /static/plugins/summernote/summernote-bs4.min.js 304 [0.02, 127.0.0.1:51915][0m
INFO 2025-04-30 21:59:40,878 runserver [36mHTTP GET /static/dist/js/pages/dashboard.js 304 [0.02, 127.0.0.1:51916][0m
INFO 2025-04-30 21:59:40,899 runserver [36mHTTP GET /static/admin/js/jquery.init.js 304 [0.03, 127.0.0.1:51914][0m
INFO 2025-04-30 21:59:40,904 runserver [36mHTTP GET /static/admin/js/core.js 304 [0.03, 127.0.0.1:51917][0m
INFO 2025-04-30 21:59:40,913 runserver [36mHTTP GET /static/admin/js/admin/RelatedObjectLookups.js 304 [0.03, 127.0.0.1:51918][0m
INFO 2025-04-30 21:59:40,918 runserver [36mHTTP GET /static/admin/js/actions.js 304 [0.03, 127.0.0.1:51915][0m
INFO 2025-04-30 21:59:40,925 runserver [36mHTTP GET /static/admin/js/urlify.js 304 [0.03, 127.0.0.1:51916][0m
INFO 2025-04-30 21:59:40,939 runserver [36mHTTP GET /static/admin/js/prepopulate.js 304 [0.03, 127.0.0.1:51913][0m
INFO 2025-04-30 21:59:40,948 runserver [36mHTTP GET /static/admin/js/vendor/xregexp/xregexp.min.js 304 [0.03, 127.0.0.1:51917][0m
INFO 2025-04-30 21:59:40,957 runserver [36mHTTP GET /static/plugins/toastr/toastr.min.js 304 [0.03, 127.0.0.1:51918][0m
INFO 2025-04-30 21:59:41,000 runserver WebSocket HANDSHAKING /ws/chat/general/ [127.0.0.1:51919]
WARNING 2025-04-30 21:59:41,221 log Not Found: /student_dashboard/dist/img/user5-128x128.jpg
WARNING 2025-04-30 21:59:41,266 runserver [33mHTTP GET /student_dashboard/dist/img/user5-128x128.jpg 404 [0.30, 127.0.0.1:51918][0m
WARNING 2025-04-30 21:59:41,267 log Not Found: /student_dashboard/dist/img/user3-128x128.jpg
WARNING 2025-04-30 21:59:41,273 log Not Found: /student_dashboard/dist/img/user7-128x128.jpg
WARNING 2025-04-30 21:59:41,279 log Not Found: /student_dashboard/dist/img/user1-128x128.jpg
WARNING 2025-04-30 21:59:41,300 runserver [33mHTTP GET /student_dashboard/dist/img/user3-128x128.jpg 404 [0.36, 127.0.0.1:51915][0m
WARNING 2025-04-30 21:59:41,304 runserver [33mHTTP GET /student_dashboard/dist/img/user7-128x128.jpg 404 [0.36, 127.0.0.1:51916][0m
WARNING 2025-04-30 21:59:41,311 runserver [33mHTTP GET /student_dashboard/dist/img/user1-128x128.jpg 404 [0.38, 127.0.0.1:51914][0m
INFO 2025-04-30 21:59:41,333 runserver WebSocket CONNECT /ws/chat/general/ [127.0.0.1:51919]
WARNING 2025-04-30 21:59:41,349 log Not Found: /student_dashboard/dist/img/user8-128x128.jpg
WARNING 2025-04-30 21:59:41,350 log Not Found: /student_dashboard/dist/img/user6-128x128.jpg
WARNING 2025-04-30 21:59:41,353 runserver [33mHTTP GET /student_dashboard/dist/img/user8-128x128.jpg 404 [0.37, 127.0.0.1:51917][0m
WARNING 2025-04-30 21:59:41,355 runserver [33mHTTP GET /student_dashboard/dist/img/user6-128x128.jpg 404 [0.36, 127.0.0.1:51913][0m
INFO 2025-04-30 21:59:41,399 runserver [mHTTP GET /api/calendar/events/?start=2025-03-30T00%3A00%3A00-04%3A00&end=2025-05-11T00%3A00%3A00-04%3A00 200 [0.12, 127.0.0.1:51918][0m
INFO 2025-04-30 21:59:46,631 runserver WebSocket DISCONNECT /ws/chat/general/ [127.0.0.1:51919]
INFO 2025-04-30 21:59:48,423 runserver WebSocket HANDSHAKING /ws/chat/general/ [127.0.0.1:51923]
INFO 2025-04-30 21:59:48,472 runserver WebSocket CONNECT /ws/chat/general/ [127.0.0.1:51923]
INFO 2025-04-30 21:59:56,335 runserver [mHTTP GET /calendar/ 200 [0.07, 127.0.0.1:51918][0m
INFO 2025-04-30 21:59:56,358 runserver WebSocket DISCONNECT /ws/chat/general/ [127.0.0.1:51923]
INFO 2025-04-30 21:59:56,531 runserver [36mHTTP GET /static/admin/js/vendor/jquery/jquery.min.js 304 [0.03, 127.0.0.1:51918][0m
INFO 2025-04-30 21:59:56,544 runserver [36mHTTP GET /static/dist/css/adminlte.min.css 304 [0.03, 127.0.0.1:51913][0m
INFO 2025-04-30 21:59:56,551 runserver [36mHTTP GET /static/plugins/overlayScrollbars/css/OverlayScrollbars.min.css 304 [0.04, 127.0.0.1:51917][0m
INFO 2025-04-30 21:59:56,555 runserver [36mHTTP GET /static/plugins/bootstrap/js/bootstrap.bundle.min.js 304 [0.03, 127.0.0.1:51915][0m
INFO 2025-04-30 21:59:56,557 runserver [36mHTTP GET /static/plugins/fontawesome-free/css/all.min.css 304 [0.04, 127.0.0.1:51914][0m
INFO 2025-04-30 21:59:56,560 runserver [36mHTTP GET /static/admin/css/forms.css 304 [0.04, 127.0.0.1:51916][0m
INFO 2025-04-30 21:59:56,587 runserver [36mHTTP GET /static/admin/css/widgets.css 304 [0.04, 127.0.0.1:51918][0m
INFO 2025-04-30 21:59:56,602 runserver [36mHTTP GET /static/plugins/summernote/summernote-bs4.min.css 304 [0.04, 127.0.0.1:51917][0m
INFO 2025-04-30 21:59:56,605 runserver [36mHTTP GET /static/plugins/toastr/toastr.min.css 304 [0.04, 127.0.0.1:51913][0m
INFO 2025-04-30 21:59:56,612 runserver [36mHTTP GET /static/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css 304 [0.03, 127.0.0.1:51916][0m
INFO 2025-04-30 21:59:56,617 runserver [36mHTTP GET /static/dist/img/user1-128x128.jpg 304 [0.03, 127.0.0.1:51914][0m
INFO 2025-04-30 21:59:56,620 runserver [36mHTTP GET /static/images/logo.png 304 [0.04, 127.0.0.1:51915][0m
INFO 2025-04-30 21:59:56,651 runserver [36mHTTP GET /static/plugins/jquery/jquery.min.js 304 [0.03, 127.0.0.1:51913][0m
INFO 2025-04-30 21:59:56,664 runserver [36mHTTP GET /static/plugins/jquery-ui/jquery-ui.min.js 304 [0.03, 127.0.0.1:51916][0m
INFO 2025-04-30 21:59:56,666 runserver [36mHTTP GET /static/dist/img/user8-128x128.jpg 304 [0.04, 127.0.0.1:51917][0m
INFO 2025-04-30 21:59:56,668 runserver [36mHTTP GET /static/dist/img/user3-128x128.jpg 304 [0.04, 127.0.0.1:51918][0m
INFO 2025-04-30 21:59:56,671 runserver [36mHTTP GET /static/dist/js/demo.js 304 [0.03, 127.0.0.1:51914][0m
INFO 2025-04-30 21:59:56,680 runserver [36mHTTP GET /static/dist/js/adminlte.min.js 304 [0.04, 127.0.0.1:51915][0m
INFO 2025-04-30 21:59:56,706 runserver [36mHTTP GET /static/dist/img/user2-160x160.jpg 304 [0.03, 127.0.0.1:51913][0m
INFO 2025-04-30 21:59:56,715 runserver [36mHTTP GET /static/plugins/moment/moment.min.js 304 [0.03, 127.0.0.1:51917][0m
INFO 2025-04-30 21:59:56,720 runserver [36mHTTP GET /static/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js 304 [0.03, 127.0.0.1:51916][0m
INFO 2025-04-30 21:59:56,728 runserver [36mHTTP GET /static/admin/js/jquery.init.js 304 [0.03, 127.0.0.1:51918][0m
INFO 2025-04-30 21:59:56,730 runserver [36mHTTP GET /static/plugins/toastr/toastr.min.js 304 [0.03, 127.0.0.1:51914][0m
INFO 2025-04-30 21:59:56,734 runserver [36mHTTP GET /static/admin/js/core.js 304 [0.03, 127.0.0.1:51915][0m
INFO 2025-04-30 21:59:56,759 runserver [36mHTTP GET /static/admin/js/admin/RelatedObjectLookups.js 304 [0.04, 127.0.0.1:51913][0m
INFO 2025-04-30 21:59:56,775 runserver [36mHTTP GET /static/admin/js/urlify.js 304 [0.04, 127.0.0.1:51916][0m
INFO 2025-04-30 21:59:56,778 runserver [36mHTTP GET /static/admin/js/actions.js 304 [0.04, 127.0.0.1:51917][0m
INFO 2025-04-30 21:59:56,783 runserver [36mHTTP GET /static/admin/js/vendor/xregexp/xregexp.min.js 304 [0.03, 127.0.0.1:51914][0m
INFO 2025-04-30 21:59:56,785 runserver [36mHTTP GET /static/admin/js/prepopulate.js 304 [0.03, 127.0.0.1:51918][0m
INFO 2025-04-30 21:59:56,790 runserver [36mHTTP GET /static/plugins/summernote/summernote-bs4.min.js 304 [0.03, 127.0.0.1:51915][0m
INFO 2025-04-30 21:59:56,873 runserver [mHTTP GET /api/calendar/events/?start=2025-03-30T00%3A00%3A00-04%3A00&end=2025-05-11T00%3A00%3A00-04%3A00 200 [0.04, 127.0.0.1:51915][0m
INFO 2025-04-30 22:00:00,555 runserver [mHTTP GET /student_dashboard/ 200 [0.06, 127.0.0.1:51915][0m
INFO 2025-04-30 22:00:00,758 runserver [36mHTTP GET /static/admin/js/vendor/jquery/jquery.min.js 304 [0.02, 127.0.0.1:51915][0m
INFO 2025-04-30 22:00:00,773 runserver [36mHTTP GET /static/dist/css/adminlte.min.css 304 [0.03, 127.0.0.1:51914][0m
INFO 2025-04-30 22:00:00,777 runserver [36mHTTP GET /static/plugins/overlayScrollbars/css/OverlayScrollbars.min.css 304 [0.03, 127.0.0.1:51918][0m
INFO 2025-04-30 22:00:00,781 runserver [36mHTTP GET /static/plugins/fontawesome-free/css/all.min.css 304 [0.03, 127.0.0.1:51916][0m
INFO 2025-04-30 22:00:00,784 runserver [36mHTTP GET /static/admin/css/forms.css 304 [0.03, 127.0.0.1:51913][0m
INFO 2025-04-30 22:00:00,787 runserver [36mHTTP GET /static/plugins/bootstrap/js/bootstrap.bundle.min.js 304 [0.04, 127.0.0.1:51917][0m
INFO 2025-04-30 22:00:00,827 runserver [36mHTTP GET /static/admin/css/widgets.css 304 [0.03, 127.0.0.1:51915][0m
INFO 2025-04-30 22:00:00,841 runserver [36mHTTP GET /static/plugins/toastr/toastr.min.css 304 [0.04, 127.0.0.1:51918][0m
INFO 2025-04-30 22:00:00,852 runserver [36mHTTP GET /static/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css 304 [0.04, 127.0.0.1:51917][0m
INFO 2025-04-30 22:00:00,855 runserver [36mHTTP GET /static/plugins/summernote/summernote-bs4.min.css 304 [0.04, 127.0.0.1:51914][0m
INFO 2025-04-30 22:00:00,858 runserver [36mHTTP GET /static/plugins/jqvmap/jqvmap.min.css 304 [0.05, 127.0.0.1:51913][0m
INFO 2025-04-30 22:00:00,865 runserver [36mHTTP GET /static/plugins/icheck-bootstrap/icheck-bootstrap.min.css 304 [0.06, 127.0.0.1:51916][0m
INFO 2025-04-30 22:00:00,876 runserver [36mHTTP GET /static/plugins/daterangepicker/daterangepicker.css 304 [0.03, 127.0.0.1:51915][0m
INFO 2025-04-30 22:00:00,929 runserver [36mHTTP GET /static/images/logo.png 304 [0.01, 127.0.0.1:51916][0m
INFO 2025-04-30 22:00:00,952 runserver [36mHTTP GET /static/dist/img/user8-128x128.jpg 304 [0.01, 127.0.0.1:51917][0m
INFO 2025-04-30 22:00:00,954 runserver [36mHTTP GET /static/dist/img/user1-128x128.jpg 304 [0.01, 127.0.0.1:51915][0m
INFO 2025-04-30 22:00:00,988 runserver [36mHTTP GET /static/dist/js/adminlte.min.js 304 [0.03, 127.0.0.1:51913][0m
INFO 2025-04-30 22:00:00,991 runserver [36mHTTP GET /static/plugins/jquery/jquery.min.js 304 [0.03, 127.0.0.1:51914][0m
INFO 2025-04-30 22:00:00,993 runserver [36mHTTP GET /static/dist/img/user3-128x128.jpg 304 [0.03, 127.0.0.1:51916][0m
INFO 2025-04-30 22:00:00,999 runserver [36mHTTP GET /static/dist/js/demo.js 304 [0.03, 127.0.0.1:51917][0m
INFO 2025-04-30 22:00:01,003 runserver [36mHTTP GET /static/plugins/jquery-ui/jquery-ui.min.js 304 [0.03, 127.0.0.1:51915][0m
INFO 2025-04-30 22:00:01,007 runserver [36mHTTP GET /static/plugins/chart.js/Chart.min.js 304 [0.02, 127.0.0.1:51918][0m
INFO 2025-04-30 22:00:01,062 runserver [36mHTTP GET /static/dist/img/user2-160x160.jpg 304 [0.01, 127.0.0.1:51913][0m
INFO 2025-04-30 22:00:01,099 runserver [36mHTTP GET /static/plugins/sparklines/sparkline.js 304 [0.03, 127.0.0.1:51918][0m
INFO 2025-04-30 22:00:01,105 runserver [36mHTTP GET /static/plugins/jqvmap/jquery.vmap.min.js 304 [0.03, 127.0.0.1:51915][0m
INFO 2025-04-30 22:00:01,107 runserver [36mHTTP GET /static/plugins/jqvmap/maps/jquery.vmap.usa.js 304 [0.04, 127.0.0.1:51917][0m
INFO 2025-04-30 22:00:01,109 runserver [36mHTTP GET /static/plugins/jquery-knob/jquery.knob.min.js 304 [0.03, 127.0.0.1:51916][0m
INFO 2025-04-30 22:00:01,112 runserver [36mHTTP GET /static/plugins/daterangepicker/daterangepicker.js 304 [0.02, 127.0.0.1:51913][0m
INFO 2025-04-30 22:00:01,113 runserver [36mHTTP GET /static/plugins/moment/moment.min.js 304 [0.03, 127.0.0.1:51914][0m
INFO 2025-04-30 22:00:01,127 runserver [36mHTTP GET /static/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js 304 [0.01, 127.0.0.1:51918][0m
INFO 2025-04-30 22:00:01,162 runserver [36mHTTP GET /static/plugins/summernote/summernote-bs4.min.js 304 [0.03, 127.0.0.1:51914][0m
INFO 2025-04-30 22:00:01,164 runserver [36mHTTP GET /static/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js 304 [0.03, 127.0.0.1:51916][0m
INFO 2025-04-30 22:00:01,167 runserver [36mHTTP GET /static/dist/js/pages/dashboard.js 304 [0.03, 127.0.0.1:51913][0m
INFO 2025-04-30 22:00:01,177 runserver [36mHTTP GET /static/admin/js/jquery.init.js 304 [0.03, 127.0.0.1:51915][0m
INFO 2025-04-30 22:00:01,180 runserver [36mHTTP GET /static/admin/js/core.js 304 [0.03, 127.0.0.1:51918][0m
INFO 2025-04-30 22:00:01,194 runserver [36mHTTP GET /static/admin/js/admin/RelatedObjectLookups.js 304 [0.04, 127.0.0.1:51917][0m
INFO 2025-04-30 22:00:01,213 runserver [36mHTTP GET /static/admin/js/urlify.js 304 [0.03, 127.0.0.1:51914][0m
INFO 2025-04-30 22:00:01,216 runserver [36mHTTP GET /static/admin/js/actions.js 304 [0.03, 127.0.0.1:51913][0m
INFO 2025-04-30 22:00:01,219 runserver [36mHTTP GET /static/admin/js/prepopulate.js 304 [0.03, 127.0.0.1:51916][0m
INFO 2025-04-30 22:00:01,226 runserver [36mHTTP GET /static/admin/js/vendor/xregexp/xregexp.min.js 304 [0.03, 127.0.0.1:51918][0m
INFO 2025-04-30 22:00:01,232 runserver [36mHTTP GET /static/plugins/toastr/toastr.min.js 304 [0.03, 127.0.0.1:51915][0m
INFO 2025-04-30 22:00:01,244 runserver WebSocket HANDSHAKING /ws/chat/general/ [127.0.0.1:51927]
INFO 2025-04-30 22:00:01,412 runserver WebSocket CONNECT /ws/chat/general/ [127.0.0.1:51927]
WARNING 2025-04-30 22:00:01,430 log Not Found: /student_dashboard/dist/img/user1-128x128.jpg
WARNING 2025-04-30 22:00:01,437 runserver [33mHTTP GET /student_dashboard/dist/img/user1-128x128.jpg 404 [0.21, 127.0.0.1:51917][0m
WARNING 2025-04-30 22:00:01,719 log Not Found: /student_dashboard/dist/img/user8-128x128.jpg
WARNING 2025-04-30 22:00:01,730 log Not Found: /student_dashboard/dist/img/user7-128x128.jpg
WARNING 2025-04-30 22:00:01,770 log Not Found: /student_dashboard/dist/img/user5-128x128.jpg
WARNING 2025-04-30 22:00:01,771 log Not Found: /student_dashboard/dist/img/user3-128x128.jpg
WARNING 2025-04-30 22:00:01,772 runserver [33mHTTP GET /student_dashboard/dist/img/user8-128x128.jpg 404 [0.51, 127.0.0.1:51913][0m
WARNING 2025-04-30 22:00:01,778 runserver [33mHTTP GET /student_dashboard/dist/img/user7-128x128.jpg 404 [0.53, 127.0.0.1:51918][0m
WARNING 2025-04-30 22:00:01,788 runserver [33mHTTP GET /student_dashboard/dist/img/user5-128x128.jpg 404 [0.54, 127.0.0.1:51916][0m
WARNING 2025-04-30 22:00:01,790 runserver [33mHTTP GET /student_dashboard/dist/img/user3-128x128.jpg 404 [0.54, 127.0.0.1:51914][0m
WARNING 2025-04-30 22:00:01,793 log Not Found: /student_dashboard/dist/img/user6-128x128.jpg
WARNING 2025-04-30 22:00:01,800 runserver [33mHTTP GET /student_dashboard/dist/img/user6-128x128.jpg 404 [0.53, 127.0.0.1:51915][0m
INFO 2025-04-30 22:00:01,834 runserver [mHTTP GET /api/calendar/events/?start=2025-03-30T00%3A00%3A00-04%3A00&end=2025-05-11T00%3A00%3A00-04%3A00 200 [0.31, 127.0.0.1:51917][0m
INFO 2025-04-30 22:00:03,828 runserver [32mHTTP GET /accounts/logout/ 302 [0.07, 127.0.0.1:51917][0m
INFO 2025-04-30 22:00:03,946 runserver [mHTTP GET / 200 [0.04, 127.0.0.1:51917][0m
INFO 2025-04-30 22:00:03,994 runserver WebSocket DISCONNECT /ws/chat/general/ [127.0.0.1:51927]
INFO 2025-04-30 22:00:09,181 views Attempting login with username: ray
INFO 2025-04-30 22:00:10,356 views User ray logged in successfully.
INFO 2025-04-30 22:00:10,381 runserver [32mHTTP POST / 302 [1.21, 127.0.0.1:51917][0m
INFO 2025-04-30 22:00:10,486 runserver [mHTTP GET /student_dashboard/ 200 [0.08, 127.0.0.1:51917][0m
INFO 2025-04-30 22:00:10,754 runserver [36mHTTP GET /static/plugins/fontawesome-free/css/all.min.css 304 [0.04, 127.0.0.1:51916][0m
INFO 2025-04-30 22:00:10,757 runserver [36mHTTP GET /static/plugins/overlayScrollbars/css/OverlayScrollbars.min.css 304 [0.04, 127.0.0.1:51914][0m
INFO 2025-04-30 22:00:10,760 runserver [36mHTTP GET /static/dist/css/adminlte.min.css 304 [0.04, 127.0.0.1:51915][0m
INFO 2025-04-30 22:00:10,763 runserver [36mHTTP GET /static/admin/css/forms.css 304 [0.05, 127.0.0.1:51913][0m
INFO 2025-04-30 22:00:10,766 runserver [36mHTTP GET /static/admin/js/vendor/jquery/jquery.min.js 304 [0.06, 127.0.0.1:51917][0m
INFO 2025-04-30 22:00:10,768 runserver [36mHTTP GET /static/plugins/bootstrap/js/bootstrap.bundle.min.js 304 [0.05, 127.0.0.1:51918][0m
INFO 2025-04-30 22:00:10,810 runserver [36mHTTP GET /static/admin/css/widgets.css 304 [0.03, 127.0.0.1:51916][0m
INFO 2025-04-30 22:00:10,814 runserver [36mHTTP GET /static/plugins/toastr/toastr.min.css 304 [0.03, 127.0.0.1:51914][0m
INFO 2025-04-30 22:00:10,818 runserver [36mHTTP GET /static/plugins/summernote/summernote-bs4.min.css 304 [0.04, 127.0.0.1:51917][0m
INFO 2025-04-30 22:00:10,831 runserver [36mHTTP GET /static/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css 304 [0.04, 127.0.0.1:51913][0m
INFO 2025-04-30 22:00:10,833 runserver [36mHTTP GET /static/plugins/icheck-bootstrap/icheck-bootstrap.min.css 304 [0.04, 127.0.0.1:51918][0m
INFO 2025-04-30 22:00:10,838 runserver [36mHTTP GET /static/plugins/jqvmap/jqvmap.min.css 304 [0.04, 127.0.0.1:51915][0m
INFO 2025-04-30 22:00:10,866 runserver [36mHTTP GET /static/plugins/daterangepicker/daterangepicker.css 304 [0.01, 127.0.0.1:51916][0m
INFO 2025-04-30 22:00:10,932 runserver [36mHTTP GET /static/images/logo.png 304 [0.03, 127.0.0.1:51916][0m
INFO 2025-04-30 22:00:10,938 runserver [36mHTTP GET /static/plugins/jquery/jquery.min.js 304 [0.03, 127.0.0.1:51915][0m
INFO 2025-04-30 22:00:10,940 runserver [36mHTTP GET /static/dist/img/user8-128x128.jpg 304 [0.03, 127.0.0.1:51913][0m
INFO 2025-04-30 22:00:10,943 runserver [36mHTTP GET /static/dist/js/adminlte.min.js 304 [0.02, 127.0.0.1:51917][0m
INFO 2025-04-30 22:00:10,945 runserver [36mHTTP GET /static/dist/img/user3-128x128.jpg 304 [0.03, 127.0.0.1:51914][0m
INFO 2025-04-30 22:00:10,948 runserver [36mHTTP GET /static/dist/img/user1-128x128.jpg 304 [0.04, 127.0.0.1:51918][0m
INFO 2025-04-30 22:00:10,960 runserver [36mHTTP GET /static/dist/js/demo.js 304 [0.01, 127.0.0.1:51916][0m
INFO 2025-04-30 22:00:10,986 runserver [36mHTTP GET /static/plugins/jquery-ui/jquery-ui.min.js 304 [0.02, 127.0.0.1:51918][0m
INFO 2025-04-30 22:00:10,995 runserver [36mHTTP GET /static/plugins/chart.js/Chart.min.js 304 [0.03, 127.0.0.1:51916][0m
INFO 2025-04-30 22:00:11,002 runserver [36mHTTP GET /static/plugins/jqvmap/maps/jquery.vmap.usa.js 304 [0.03, 127.0.0.1:51913][0m
INFO 2025-04-30 22:00:11,004 runserver [36mHTTP GET /static/plugins/sparklines/sparkline.js 304 [0.03, 127.0.0.1:51915][0m
INFO 2025-04-30 22:00:11,006 runserver [36mHTTP GET /static/plugins/jqvmap/jquery.vmap.min.js 304 [0.03, 127.0.0.1:51914][0m
INFO 2025-04-30 22:00:11,008 runserver [36mHTTP GET /static/plugins/jquery-knob/jquery.knob.min.js 304 [0.02, 127.0.0.1:51917][0m
INFO 2025-04-30 22:00:11,020 runserver [36mHTTP GET /static/plugins/moment/moment.min.js 304 [0.02, 127.0.0.1:51918][0m
INFO 2025-04-30 22:00:11,036 runserver [36mHTTP GET /static/plugins/daterangepicker/daterangepicker.js 304 [0.03, 127.0.0.1:51916][0m
INFO 2025-04-30 22:00:11,046 runserver [36mHTTP GET /static/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js 304 [0.03, 127.0.0.1:51915][0m
INFO 2025-04-30 22:00:11,054 runserver [36mHTTP GET /static/plugins/summernote/summernote-bs4.min.js 304 [0.03, 127.0.0.1:51917][0m
INFO 2025-04-30 22:00:11,061 runserver [36mHTTP GET /static/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js 304 [0.03, 127.0.0.1:51914][0m
INFO 2025-04-30 22:00:11,062 runserver [36mHTTP GET /static/dist/js/pages/dashboard.js 304 [0.03, 127.0.0.1:51913][0m
INFO 2025-04-30 22:00:11,064 runserver [36mHTTP GET /static/admin/js/jquery.init.js 304 [0.03, 127.0.0.1:51918][0m
INFO 2025-04-30 22:00:11,077 runserver [36mHTTP GET /static/admin/js/core.js 304 [0.02, 127.0.0.1:51916][0m
INFO 2025-04-30 22:00:11,083 runserver [36mHTTP GET /static/admin/js/admin/RelatedObjectLookups.js 304 [0.02, 127.0.0.1:51915][0m
INFO 2025-04-30 22:00:11,096 runserver [36mHTTP GET /static/admin/js/actions.js 304 [0.02, 127.0.0.1:51917][0m
INFO 2025-04-30 22:00:11,116 runserver [36mHTTP GET /static/admin/js/prepopulate.js 304 [0.02, 127.0.0.1:51918][0m
INFO 2025-04-30 22:00:11,118 runserver [36mHTTP GET /static/admin/js/urlify.js 304 [0.03, 127.0.0.1:51914][0m
INFO 2025-04-30 22:00:11,122 runserver [36mHTTP GET /static/admin/js/vendor/xregexp/xregexp.min.js 304 [0.03, 127.0.0.1:51913][0m
INFO 2025-04-30 22:00:11,129 runserver [36mHTTP GET /static/plugins/toastr/toastr.min.js 304 [0.03, 127.0.0.1:51915][0m
INFO 2025-04-30 22:00:11,135 runserver WebSocket HANDSHAKING /ws/chat/general/ [127.0.0.1:51932]
INFO 2025-04-30 22:00:11,152 runserver [36mHTTP GET /static/dist/img/user2-160x160.jpg 304 [0.04, 127.0.0.1:51917][0m
INFO 2025-04-30 22:00:11,288 runserver WebSocket CONNECT /ws/chat/general/ [127.0.0.1:51932]
WARNING 2025-04-30 22:00:11,317 log Not Found: /student_dashboard/dist/img/user1-128x128.jpg
WARNING 2025-04-30 22:00:11,340 runserver [33mHTTP GET /student_dashboard/dist/img/user1-128x128.jpg 404 [0.23, 127.0.0.1:51916][0m
WARNING 2025-04-30 22:00:11,620 log Not Found: /student_dashboard/dist/img/user6-128x128.jpg
WARNING 2025-04-30 22:00:11,623 log Not Found: /student_dashboard/dist/img/user5-128x128.jpg
WARNING 2025-04-30 22:00:11,626 log Not Found: /student_dashboard/dist/img/user7-128x128.jpg
WARNING 2025-04-30 22:00:11,627 log Not Found: /student_dashboard/dist/img/user3-128x128.jpg
WARNING 2025-04-30 22:00:11,634 runserver [33mHTTP GET /student_dashboard/dist/img/user6-128x128.jpg 404 [0.48, 127.0.0.1:51915][0m
WARNING 2025-04-30 22:00:11,685 runserver [33mHTTP GET /student_dashboard/dist/img/user5-128x128.jpg 404 [0.54, 127.0.0.1:51918][0m
WARNING 2025-04-30 22:00:11,692 runserver [33mHTTP GET /student_dashboard/dist/img/user7-128x128.jpg 404 [0.55, 127.0.0.1:51913][0m
WARNING 2025-04-30 22:00:11,695 runserver [33mHTTP GET /student_dashboard/dist/img/user3-128x128.jpg 404 [0.55, 127.0.0.1:51914][0m
WARNING 2025-04-30 22:00:11,705 log Not Found: /student_dashboard/dist/img/user8-128x128.jpg
WARNING 2025-04-30 22:00:11,718 runserver [33mHTTP GET /student_dashboard/dist/img/user8-128x128.jpg 404 [0.52, 127.0.0.1:51917][0m
INFO 2025-04-30 22:00:11,737 runserver [mHTTP GET /api/calendar/events/?start=2025-03-30T00%3A00%3A00-04%3A00&end=2025-05-11T00%3A00%3A00-04%3A00 200 [0.38, 127.0.0.1:51916][0m
INFO 2025-05-05 17:57:02,231 autoreload Watching for file changes with StatReloader
ERROR 2025-05-05 17:57:07,154 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: portal_customuser.dojo_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\deprecation.py", line 146, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\Dojo-App\portal\middleware.py", line 26, in process_request
    if request.user.is_authenticated:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\functional.py", line 266, in inner
    self._setup()
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 198, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\backends.py", line 161, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: portal_customuser.dojo_id
ERROR 2025-05-05 17:57:07,187 runserver [35;1mHTTP GET / 500 [0.45, 127.0.0.1:50570][0m
INFO 2025-05-05 17:57:42,386 autoreload Watching for file changes with StatReloader
ERROR 2025-05-05 17:57:43,474 log Internal Server Error: /api/calendar/events/
Traceback (most recent call last):
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: portal_customuser.dojo_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\deprecation.py", line 146, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\Dojo-App\portal\middleware.py", line 26, in process_request
    if request.user.is_authenticated:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\functional.py", line 266, in inner
    self._setup()
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 198, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\backends.py", line 161, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: portal_customuser.dojo_id
ERROR 2025-05-05 17:57:43,501 log Internal Server Error: /api/calendar/events/
ERROR 2025-05-05 17:57:43,502 runserver [35;1mHTTP GET /api/calendar/events/?start=2025-04-27T00%3A00%3A00-04%3A00&end=2025-06-08T00%3A00%3A00-04%3A00 500 [0.11, 127.0.0.1:50591][0m
ERROR 2025-05-05 17:57:46,489 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: portal_customuser.dojo_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\deprecation.py", line 146, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\Dojo-App\portal\middleware.py", line 26, in process_request
    if request.user.is_authenticated:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\functional.py", line 266, in inner
    self._setup()
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 198, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\backends.py", line 161, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: portal_customuser.dojo_id
ERROR 2025-05-05 17:57:46,499 runserver [35;1mHTTP GET / 500 [0.08, 127.0.0.1:50591][0m
ERROR 2025-05-05 17:58:00,820 log Internal Server Error: /api/calendar/events/
Traceback (most recent call last):
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: portal_customuser.dojo_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\deprecation.py", line 146, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\Dojo-App\portal\middleware.py", line 26, in process_request
    if request.user.is_authenticated:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\functional.py", line 266, in inner
    self._setup()
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 198, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\backends.py", line 161, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: portal_customuser.dojo_id
ERROR 2025-05-05 17:58:00,836 log Internal Server Error: /api/calendar/events/
ERROR 2025-05-05 17:58:00,836 runserver [35;1mHTTP GET /api/calendar/events/?start=2025-04-27T00%3A00%3A00-04%3A00&end=2025-06-08T00%3A00%3A00-04%3A00 500 [0.08, 127.0.0.1:50595][0m
ERROR 2025-05-05 17:58:43,427 log Internal Server Error: /api/calendar/events/
Traceback (most recent call last):
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: portal_customuser.dojo_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\deprecation.py", line 146, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\Dojo-App\portal\middleware.py", line 26, in process_request
    if request.user.is_authenticated:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\functional.py", line 266, in inner
    self._setup()
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 198, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\backends.py", line 161, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: portal_customuser.dojo_id
ERROR 2025-05-05 17:58:43,439 log Internal Server Error: /api/calendar/events/
ERROR 2025-05-05 17:58:43,440 runserver [35;1mHTTP GET /api/calendar/events/?start=2025-04-27T00%3A00%3A00-04%3A00&end=2025-06-08T00%3A00%3A00-04%3A00 500 [0.05, 127.0.0.1:50611][0m
ERROR 2025-05-05 17:59:00,801 log Internal Server Error: /api/calendar/events/
Traceback (most recent call last):
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: portal_customuser.dojo_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\deprecation.py", line 146, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\Dojo-App\portal\middleware.py", line 26, in process_request
    if request.user.is_authenticated:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\functional.py", line 266, in inner
    self._setup()
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 198, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\backends.py", line 161, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: portal_customuser.dojo_id
ERROR 2025-05-05 17:59:00,825 log Internal Server Error: /api/calendar/events/
ERROR 2025-05-05 17:59:00,826 runserver [35;1mHTTP GET /api/calendar/events/?start=2025-04-27T00%3A00%3A00-04%3A00&end=2025-06-08T00%3A00%3A00-04%3A00 500 [0.07, 127.0.0.1:50617][0m
INFO 2025-05-05 17:59:49,303 autoreload Watching for file changes with StatReloader
ERROR 2025-05-05 17:59:54,437 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: portal_customuser.dojo_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\deprecation.py", line 146, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\Dojo-App\portal\middleware.py", line 26, in process_request
    if request.user.is_authenticated:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\functional.py", line 266, in inner
    self._setup()
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 198, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\backends.py", line 161, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: portal_customuser.dojo_id
ERROR 2025-05-05 17:59:54,450 runserver [35;1mHTTP GET / 500 [0.12, 127.0.0.1:50642][0m
ERROR 2025-05-05 18:00:01,474 log Internal Server Error: /api/calendar/events/
Traceback (most recent call last):
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: portal_customuser.dojo_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\deprecation.py", line 146, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\Dojo-App\portal\middleware.py", line 26, in process_request
    if request.user.is_authenticated:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\functional.py", line 266, in inner
    self._setup()
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 198, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\backends.py", line 161, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: portal_customuser.dojo_id
ERROR 2025-05-05 18:00:01,496 log Internal Server Error: /api/calendar/events/
ERROR 2025-05-05 18:00:01,497 runserver [35;1mHTTP GET /api/calendar/events/?start=2025-04-27T00%3A00%3A00-04%3A00&end=2025-06-08T00%3A00%3A00-04%3A00 500 [0.10, 127.0.0.1:50645][0m
ERROR 2025-05-05 18:00:44,431 log Internal Server Error: /api/calendar/events/
Traceback (most recent call last):
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: portal_customuser.dojo_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\deprecation.py", line 146, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\Dojo-App\portal\middleware.py", line 26, in process_request
    if request.user.is_authenticated:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\functional.py", line 266, in inner
    self._setup()
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 198, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\backends.py", line 161, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: portal_customuser.dojo_id
ERROR 2025-05-05 18:00:44,443 log Internal Server Error: /api/calendar/events/
ERROR 2025-05-05 18:00:44,446 runserver [35;1mHTTP GET /api/calendar/events/?start=2025-04-27T00%3A00%3A00-04%3A00&end=2025-06-08T00%3A00%3A00-04%3A00 500 [0.06, 127.0.0.1:50701][0m
ERROR 2025-05-05 18:01:01,441 log Internal Server Error: /api/calendar/events/
Traceback (most recent call last):
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: portal_customuser.dojo_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\deprecation.py", line 146, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\Dojo-App\portal\middleware.py", line 26, in process_request
    if request.user.is_authenticated:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\functional.py", line 266, in inner
    self._setup()
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 198, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\backends.py", line 161, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: portal_customuser.dojo_id
ERROR 2025-05-05 18:01:01,454 log Internal Server Error: /api/calendar/events/
ERROR 2025-05-05 18:01:01,459 runserver [35;1mHTTP GET /api/calendar/events/?start=2025-04-27T00%3A00%3A00-04%3A00&end=2025-06-08T00%3A00%3A00-04%3A00 500 [0.06, 127.0.0.1:50710][0m
ERROR 2025-05-05 18:01:45,447 log Internal Server Error: /api/calendar/events/
Traceback (most recent call last):
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: portal_customuser.dojo_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\deprecation.py", line 146, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\Dojo-App\portal\middleware.py", line 26, in process_request
    if request.user.is_authenticated:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\functional.py", line 266, in inner
    self._setup()
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 198, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\backends.py", line 161, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: portal_customuser.dojo_id
ERROR 2025-05-05 18:01:45,460 log Internal Server Error: /api/calendar/events/
ERROR 2025-05-05 18:01:45,461 runserver [35;1mHTTP GET /api/calendar/events/?start=2025-04-27T00%3A00%3A00-04%3A00&end=2025-06-08T00%3A00%3A00-04%3A00 500 [0.06, 127.0.0.1:50746][0m
ERROR 2025-05-05 18:02:00,796 log Internal Server Error: /api/calendar/events/
Traceback (most recent call last):
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: portal_customuser.dojo_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\deprecation.py", line 146, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\Dojo-App\portal\middleware.py", line 26, in process_request
    if request.user.is_authenticated:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\functional.py", line 266, in inner
    self._setup()
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\utils\functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 198, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\contrib\auth\backends.py", line 161, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kai\Onedojo\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: portal_customuser.dojo_id
ERROR 2025-05-05 18:02:00,803 log Internal Server Error: /api/calendar/events/
ERROR 2025-05-05 18:02:00,804 runserver [35;1mHTTP GET /api/calendar/events/?start=2025-04-27T00%3A00%3A00-04%3A00&end=2025-06-08T00%3A00%3A00-04%3A00 500 [0.05, 127.0.0.1:50751][0m
